#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))

$dir/back/build-linux
$dir/front/build-linux

mkdir -p $dir/publish/linux

cp -rf $dir/back/Measure/Measure.Unix/bin/Publish/Linux64/Measure.Unix $dir/publish/linux/

cp -rf $dir/src/* $dir/publish/linux

cp -rf $dir/front/out/deco2me-linux-x64/* $dir/publish/linux

cp -rf $dir/setup/linux/* $dir/publish/linux

mv $dir/publish/linux/Measure.Unix $dir/publish/linux/Measure