#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))


sudo $PWD/back/build-mac
sudo $PWD/front/build-mac

mkdir -p $PWD/publish/mac
mkdir -p $PWD/publish/mac/deCo2me
mkdir -p $PWD/publish/mac/deCo2me/back
mkdir -p $PWD/publish/mac/deCo2me/front
mkdir -p $PWD/publish/mac/deCo2me/front/data


sudo mv $PWD/back/Measure/Measure.Unix/bin/Publish/Mac64/Measure.Unix $PWD/publish/mac/deCo2me/back/Measure
#cp -rf $PWD/back/Measure/Measure.Unix/bin/Publish/Mac64/*.dylib $PWD/publish/mac/deCo2me/

#cp -rf $PWD/back/Measure/Measure.Unix/bin/Publish/Mac64/*.exe $PWD/publish/mac/deCo2me/
cp -rf $PWD/back/Measure/Measure.Unix/bin/Publish/Mac64/* $PWD/publish/mac/deCo2me/back

cp -rf $PWD/src/* $PWD/publish/mac/deCo2me/back

cp -rf $PWD/front/out/deco2me-darwin-x64/* $PWD/publish/mac/deCo2me/front

cp -rf $PWD/setup/mac/installer.sh $PWD/publish/mac/deCo2me
cp -rf $PWD/setup/mac/uninstaller.sh $PWD/publish/mac/deCo2me
cp -rf $PWD/setup/mac/starter.sh $PWD/publish/mac/deCo2me/front




