#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))

$dir/back/build-mac
$dir/front/build-mac

mkdir -p $dir/publish/mac

cp -rf $dir/back/Measure/Measure.Unix/bin/Publish/Mac64/Measure.Unix $dir/publish/mac/
cp -rf $dir/back/Measure/Measure.Unix/bin/Publish/Mac64/*.dylib $dir/publish/mac

cp -rf $dir/back/Measure/Measure.Unix/bin/Publish/Mac64/*.exe $dir/publish/mac
cp -rf $dir/back/Measure/Measure.Unix/bin/Publish/Mac64/*.dll $dir/publish/mac

cp -rf $dir/src/* $dir/publish/mac

cp -rf $dir/front/out/deco2me-darwin-x64/* $dir/publish/mac

cp -rf $dir/setup/mac/* $dir/publish/mac

mv $dir/publish/mac/Measure.Unix $dir/publish/mac/Measure