#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))

rm -rf $PWD/back/Measure/Measure.Common/bin/Release
rm -rf $PWD/back/Measure/Measure.Unix/bin/Release
dotnet publish $PWD/back/Measure/Measure.Unix -c Release -o $PWD/back/Measure/Measure.Unix/bin/Publish/Mac64 -f net5.0 -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
