#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))

rm -rf $dir/Measure.Common/bin/Release
rm -rf $dir/Measure.Unix/bin/Release
dotnet publish $dir/Measure.Unix -c Release -o $dir/Measure.Unix/bin/Publish/Linux64 -f net5.0 -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true