#!/bin/bash
dir=$(dirname $(readlink /proc/$$/fd/255))

rm -rf $dir/LibreHardwareMonitorLib/bin/Release
rm -rf $dir/Measure.Common/bin/Release
rm -rf $dir/Measure.Win/bin/Release
dotnet publish $dir/Measure.Win -c Release -o $dir/Measure.Win/bin/Publish -f net5.0-windows -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true